name: Build and Deploy

on: 
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_web:
    name: Build (web)

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Install Rust Toolchain
        run: rustup default stable

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build (web)
        run: wasm-pack build --target web

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:  
          path: pkg/
    

  deploy:
    name: Deploy to GitHub Pages

    environment:
      name: github-pages

    runs-on: ubuntu-latest
    needs: build_web

    permissions:
      pages: write
      id-token: write 

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
